# Generated by Django 5.1.2 on 2025-01-18 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_contact_mobile_name', models.CharField(max_length=50)),
                ('user_contact_mobile_number', models.CharField(max_length=15)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.user_data')),
            ],
        ),
    ]
