# Generated by Django 5.1.2 on 2025-01-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_ph_no', models.CharField(max_length=15)),
                ('user_id', models.CharField(max_length=15, unique=True)),
                ('user_password', models.CharField(max_length=50)),
            ],
        ),
    ]
