# Generated by Django 5.1.2 on 2025-01-16 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('user_mobile_no', models.CharField(max_length=15, unique=True)),
                ('user_email', models.CharField(max_length=15)),
                ('user_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_contact_mobile_name', models.CharField(max_length=50)),
                ('user_contact_mobile_number', models.CharField(max_length=15)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.user_data')),
            ],
        ),
    ]
